### ISSUE TITLE
Aggregate fails if pipeline results in Missing value.

### ISSUE THREAD

**Issue by mattsdavis** [bwaldvogel/mongo-java-server#111]
With a document such as: 

```json
{
    "_id" : ObjectId("5e0685f65ac63194d3408621"),
    "content" : {
        "key" : "value",
        "key2" : "value2"
    }
}
```

The following aggregate works in the shell against MongoDB:

```json
db.temp.aggregate([{$group:{
    _id:"$_id", 
    sources:{
        $addToSet:{
            "key":"$content.key",
            "missing":"$content.missing"
            }
        }
     }
}])
```

But fails when using mongo-java-server with the following stack trace: 
```
[DEBUG] 2019-12-27 14:44:32.318 [mongo-server-worker2] MongoWireProtocolHandler - query {aggregate=temp, pipeline=[{$group={_id=$_id, sources={$addToSet={missing=$content.missing, key=$content.key}}}}], cursor={}} from testdb.$cmd
[DEBUG] 2019-12-27 14:44:32.320 [mongo-server-worker2] MongoWireProtocolHandler - MongoQuery(header: MessageHeader(request: 9, responseTo: 0), collection: testdb.$cmd, query: {"aggregate" : "temp", "pipeline" : [ { "$group" : { "_id" : "$_id", "sources" : { "$addToSet" : { "missing" : "$content.missing", "key" : "$content.key" } } } } ], "cursor" : {}}, returnFieldSelector: null)
[ERROR] 2019-12-27 14:44:32.376 [mongo-server-worker2] MongoWireEncoder - Failed to encode {cursor={id=0, ns=testdb.temp, firstBatch=[{_id=ObjectId[5e06894f24af13c5642a61c9], sources=[{missing=de.bwaldvogel.mongo.backend.Missing@1119f65d, key=value}]}]}, ok=1.0}
java.lang.IllegalArgumentException: Unknown type: class de.bwaldvogel.mongo.backend.Missing
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.determineType(BsonEncoder.java:193) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeValue(BsonEncoder.java:57) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeDocument(BsonEncoder.java:33) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeValue(BsonEncoder.java:74) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeValue(BsonEncoder.java:60) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeDocument(BsonEncoder.java:33) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeValue(BsonEncoder.java:82) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeValue(BsonEncoder.java:60) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeDocument(BsonEncoder.java:33) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeValue(BsonEncoder.java:74) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeValue(BsonEncoder.java:60) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeDocument(BsonEncoder.java:33) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeValue(BsonEncoder.java:82) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeValue(BsonEncoder.java:60) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeDocument(BsonEncoder.java:33) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeValue(BsonEncoder.java:74) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeValue(BsonEncoder.java:60) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.bson.BsonEncoder.encodeDocument(BsonEncoder.java:33) ~[mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.MongoWireEncoder.encode(MongoWireEncoder.java:36) [mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.MongoWireEncoder.encode(MongoWireEncoder.java:15) [mongo-java-server-core-1.23.0.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-codec-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:763) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:789) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:812) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1037) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:293) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:71) [mongo-java-server-core-1.23.0.jar:?]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:36) [mongo-java-server-core-1.23.0.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328) [netty-codec-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302) [netty-codec-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by bwaldvogel** [comment]
Thanks for reporting this bug. It should be fixed with 5e5c5589bc3e86bf51e5aec456dcf82c695cf7fd. Can you confirm this?

**Comment by mattsdavis** [comment]
I've never used gradle and I don't have it in the environment that my test is in so I can't easily build the jar and test it. Here's my jUnit test:

```java

import com.mongodb.Block;
import com.mongodb.ServerAddress;
import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.model.Accumulators;
import com.mongodb.client.model.Aggregates;
import de.bwaldvogel.mongo.MongoServer;
import de.bwaldvogel.mongo.backend.memory.MemoryBackend;
import java.net.InetSocketAddress;
import java.util.Arrays;
import org.bson.Document;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

public class MongoJavaServerMissingValueTest {

  private MongoServer server;
  private MongoClient client;
  private MongoCollection<Document> collection;

  @Before
  public void setUp(){
    server = new MongoServer(new MemoryBackend());
    InetSocketAddress serverAddress = server.bind();
    client = new MongoClient(new ServerAddress(serverAddress));
    collection = client.getDatabase("testdb")
        .getCollection("testcollection");
    Document obj = new Document("content",new Document("key","value").append("key2","value2"));
    collection.insertOne(obj);
  }

  @After
  public void tearDown(){
    client.close();
    server.shutdown();
  }

  Block<Document> printBlock = new Block<Document>() {
    @Override
    public void apply(Document document) {
      System.out.println(document.toJson());
    }
  };

  @Test
  public void testAggregateWithMissingValue(){
    collection.aggregate(Arrays.asList(
        Aggregates.group("$_id",
            Accumulators.addToSet("sources",new Document("missing", "$content.missing").append("key","$content.key")))
    )).forEach(printBlock);
  }
}
```

**Comment by bwaldvogel** [comment]
It’s basically the same test as I’ve introduced in https://github.com/bwaldvogel/mongo-java-server/commit/5e5c5589bc3e86bf51e5aec456dcf82c695cf7fd#diff-cff016b4dd355a4e76a930ef03a93e4aR476.
So I’ll publish a new version soon which will contain the fix.

**Comment by bwaldvogel** [comment]
Version `1.24.0` contains the fix.
