### ISSUE TITLE
new Update().inc() BigDecimal128 error

### ISSUE THREAD

**Issue by baotoushashou** [bwaldvogel/mongo-java-server#112]
When i updated my field which is the type of BigDecimal, i got the error as follows:

`java.lang.UnsupportedOperationException: cannot calculate on 1.22 and 1.22
	at de.bwaldvogel.mongo.backend.NumericUtils.calculate(NumericUtils.java:41)
	at de.bwaldvogel.mongo.backend.NumericUtils.addNumbers(NumericUtils.java:46)
	at de.bwaldvogel.mongo.backend.FieldUpdates.handleIncMul(FieldUpdates.java:279)
	at de.bwaldvogel.mongo.backend.FieldUpdates.apply(FieldUpdates.java:99)
	at de.bwaldvogel.mongo.backend.FieldUpdates.apply(FieldUpdates.java:59)
	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.modifyField(AbstractMongoCollection.java:236)
	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.calculateUpdateDocument(AbstractMongoCollection.java:323)
	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.updateDocument(AbstractMongoCollection.java:540)
	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.updateDocuments(AbstractMongoCollection.java:510)
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.updateDocuments(AbstractMongoDatabase.java:843)
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.commandUpdate(AbstractMongoDatabase.java:292)
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.handleCommand(AbstractMongoDatabase.java:121)
	at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleCommand(AbstractMongoBackend.java:203)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleCommand(MongoDatabaseHandler.java:154)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleQuery(MongoDatabaseHandler.java:91)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:71)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:36)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)`

I have checked the source code of the mongo-java-server.
It seems that the mock server doesn't support the type of Bigdecimal When using the operator of 'inc'.
The environment includes the server of mongodb4.2.2, the diver of 3.11.2, junit of 5.5.2.
When using the real mongodb4.2.2 in development environment , the operation was successful.But when using mongo-java-server in test environment, it was error.

**Comment by bwaldvogel** [comment]
I’ve added support in 341b84a179f9a063eaa44202271673f39da729ad. Could you test it?

**Comment by bwaldvogel** [comment]
The change is available in version `1.25.0`.
