### ISSUE TITLE
Range query with MinKey and MaxKey throws exception

### ISSUE THREAD

**Issue by advptr** [bwaldvogel/mongo-java-server#114]
Trying to perform a  composite index range query with MinKey and MaxKey, and MongoDB works fine but not mongo-java-server (for unit tests). Example log output: 

```
10:30:06.350 [mongo-server-worker3] DEBUG de.bwaldvogel.mongo.wire.MongoWireProtocolHandler - query {"_id" : {
"$gt" : {"item" : "itemValue", "attribute" : "attrValue", "hash" : "de.bwaldvogel.mongo.bson.MinKey@2e1a3049"}, 
"$lt" : {"item" : "itemValue", "attribute" : "attrValue", "hash" : "de.bwaldvogel.mongo.bson.MaxKey@6676c267"}}} from testdb.testcollection

10:30:06.351 [mongo-server-worker3] ERROR de.bwaldvogel.mongo.wire.MongoExceptionHandler - exception for client 12c9af1e
java.lang.UnsupportedOperationException: can't sort class de.bwaldvogel.mongo.bson.MinKey
	at de.bwaldvogel.mongo.backend.ValueComparator.getTypeOrder(ValueComparator.java:272)
	at de.bwaldvogel.mongo.backend.ValueComparator.compareTypes(ValueComparator.java:76)
	at de.bwaldvogel.mongo.backend.ValueComparator.compareDocuments(ValueComparator.java:241)
	at de.bwaldvogel.mongo.backend.ValueComparator.doCompare(ValueComparator.java:171)
	at de.bwaldvogel.mongo.backend.ValueComparator.compare(ValueComparator.java:82)
	at de.bwaldvogel.mongo.backend.DefaultQueryMatcher.checkExpressionMatch(DefaultQueryMatcher.java:466)
...
```

**Comment by bwaldvogel** [comment]
Version `1.24.0` contains your fix, thanks!

**Comment by advptr** [comment]
Brilliant, thanks a lot!
