### ISSUE TITLE
Support for Collation (since 3.4) feature

### ISSUE THREAD

**Issue by eryabitskiy** [bwaldvogel/mongo-java-server#116]
There is Collation feature, since 3.4 version
https://docs.mongodb.com/manual/reference/collation/
Some of unit tests rely on indexes and some of index are using collation. And collation is not supported.
Basically it is a blocker to have all unit tests using only mongo-java-server. Currently we have half of tests over mongo-java-server and half over local mongo db instance. 

Would be really great to have this feature supported!

Now when you try to create any index with collation option, using mongo-java-server (memory backed), you get exception

```
java.lang.IllegalArgumentException: Collation not supported by server version: ServerVersion{versionList=[3, 0, 0]}

	at com.mongodb.operation.OperationHelper.validateCollation(OperationHelper.java:127)
	at com.mongodb.operation.OperationHelper.validateCollation(OperationHelper.java:122)
	at com.mongodb.operation.OperationHelper.validateIndexRequestCollations(OperationHelper.java:197)
	at com.mongodb.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:176)
	at com.mongodb.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:172)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:530)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:492)
	at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:172)
	at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:72)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:206)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:175)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:1698)
```

**Comment by deniszpua** [comment]
Use  `MongoServer server = new MongoServer(new MemoryBackend().version(ServerVersion.MONGO_3_6));` to fix the issue like above.

**Comment by bwaldvogel** [comment]
@deniszpua: Thanks for the quick clarification!
@eryabitskiy: Does it work for you?

We need to at least improve the README but I’m actually thinking to make it the new default.

**Comment by eryabitskiy** [comment]
@bwaldvogel it works! I guess we can close this ticket.
