### ISSUE TITLE
Support of $unset stage in aggregate pipeline 

### ISSUE THREAD

**Issue by max3163** [bwaldvogel/mongo-java-server#118]
Please could you add more stage for aggregator pipeline method. 
Actually I got this error for $unset stage :

com.mongodb.MongoCommandException: Command failed with error 40324 (Location40324): 'Unrecognized pipeline stage name: '$unset'' on server 127.0.0.1:57250. The full response is {"$err": "Unrecognized pipeline stage name: '$unset'", "errmsg": "Unrecognized pipeline stage name: '$unset'", "code": 40324, "codeName": "Location40324", "ok": 0}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:175)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:303)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:259)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:450)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:226)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:343)
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:334)
	at com.mongodb.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:220)
	at com.mongodb.operation.CommandOperationHelper$5.call(CommandOperationHelper.java:206)
	at com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463)
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:203)
	at com.mongodb.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:200)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:333)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:42)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:196)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:143)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:39)
	at com.google.common.collect.Lists.newArrayList(Lists.java:130)

**Comment by markbigler** [comment]
It shouldn't be a big deal.

Unfortunately, I don't have much time right now, but I'll take a quick look at it.

**Comment by markbigler** [comment]
As a workaround you could use `{ $project: { "<field>": 0 } }` instead of `{ $unset: "<field>" }`.

https://docs.mongodb.com/manual/reference/operator/aggregation/unset/#considerations

**Comment by bwaldvogel** [comment]
Available in version `1.25.0`.

**Comment by max3163** [comment]
Not yet available in maven repo :

https://mvnrepository.com/artifact/de.bwaldvogel/mongo-java-server

I will test it when it wil be the case.

**Comment by bwaldvogel** [comment]
Apparently my release to Maven Central did not work for some reason. I need to investigate…

**Comment by bwaldvogel** [comment]
The release failed because of https://issues.sonatype.org/browse/MVNCENTRAL-5276.
I’ll try to re-release without SHA-256/SHA-512 checksums as this issue is currently blocking the release.

**Comment by bwaldvogel** [comment]
It’s available now.

**Comment by max3163** [comment]
Still nothing for me at : https://mvnrepository.com/artifact/de.bwaldvogel/mongo-java-server

**Comment by bwaldvogel** [comment]
`mvnrepository.com` uses and index which might not be updated yet.
The repository itself contains the artifacts: https://repo1.maven.org/maven2/de/bwaldvogel/mongo-java-server/1.25.0/

**Comment by max3163** [comment]
Ok, I got it now. it work ! Thanks. 
I have a new error now, I will open a new ticket.
