### ISSUE TITLE
Lookup Stage failed when no value

### ISSUE THREAD

**Issue by max3163** [bwaldvogel/mongo-java-server#123]
I have a lookup stage on two collections and sometime the value is not present in the other collection. 
With mongodb it's not a problem but with your implementation it crash : 

`4807 [mongo-server-worker2] ERROR d.b.m.wire.MongoExceptionHandler - exception for client 2bc4fedf 
java.lang.NullPointerException: null
	at de.bwaldvogel.mongo.backend.aggregation.stage.LookupStage.lookupValue(LookupStage.java:63)
	at de.bwaldvogel.mongo.backend.aggregation.stage.LookupStage.resolveRemoteField(LookupStage.java:50)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:199)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:400)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:503)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at de.bwaldvogel.mongo.backend.aggregation.Aggregation.runStages(Aggregation.java:158)
	at de.bwaldvogel.mongo.backend.aggregation.Aggregation.runStages(Aggregation.java:145)`

I use the lookup like this : 
`           pipeline.add(Aggregates.lookup(MongoHandler.RESULT_COLLECTION, "_id", "_id", "result"));
            pipeline.add(Aggregates.unwind("$result", new UnwindOptions().preserveNullAndEmptyArrays(true)));`

**Comment by max3163** [comment]
My bad, only the collection need to exist in fact
I can live with that !

**Comment by bwaldvogel** [comment]
Thanks for reporting this issue. I’ve fixed missing collection handling in fdadab9a829edb6c657f9491eaf68f28e8960908.
