### ISSUE TITLE
Degradation from 1.30.0 to 1.31.0: replaceOne and findOneAndReplace backward compatibility is broken

### ISSUE THREAD

**Issue by eryabitskiy** [bwaldvogel/mongo-java-server#154]
After update from 1.30.0 got errors for replaceOne and findOneAndReplace with conditional updates. Which are used for optimistic locking (conditional document replacement).

Code to reproduce (classic scenario where I have revision field which is incremented on every document modification, so I check both _id and revision field as a condition for update:
**Also there should be secondary index over any field.**

```
mongoCollection.replaceOne(
                and(
                        eq(entityId),
                        eq("revision", originalRevision)
                ),
                entity
        )
```

result exception:

```
java.lang.UnsupportedOperationException: null
	at de.bwaldvogel.mongo.backend.EmptyIndex.checkUpdate(EmptyIndex.java:57) ~[mongo-java-server-core-1.31.0.jar:?]
	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.updateDocument(AbstractMongoCollection.java:568) ~[mongo-java-server-core-1.31.0.jar:?]
	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.updateDocuments(AbstractMongoCollection.java:532) ~[mongo-java-server-core-1.31.0.jar:?]
	at de.bwaldvogel.mongo.backend.AbstractSynchronizedMongoCollection.updateDocuments(AbstractSynchronizedMongoCollection.java:51) ~[mongo-java-server-core-1.31.0.jar:?]
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.updateDocuments(AbstractMongoDatabase.java:846) ~[mongo-java-server-core-1.31.0.jar:?]
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.commandUpdate(AbstractMongoDatabase.java:286) ~[mongo-java-server-core-1.31.0.jar:?]
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.handleCommand(AbstractMongoDatabase.java:113) ~[mongo-java-server-core-1.31.0.jar:?]
	at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleCommand(AbstractMongoBackend.java:334) ~[mongo-java-server-core-1.31.0.jar:?]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleCommand(MongoDatabaseHandler.java:201) ~[mongo-java-server-core-1.31.0.jar:?]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleQuery(MongoDatabaseHandler.java:111) ~[mongo-java-server-core-1.31.0.jar:?]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:68) ~[mongo-java-server-core-1.31.0.jar:?]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:35) ~[mongo-java-server-core-1.31.0.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

code to reproduce:

```
package test;

import com.mongodb.MongoClient;
import com.mongodb.ServerAddress;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.model.Indexes;
import de.bwaldvogel.mongo.MongoServer;
import de.bwaldvogel.mongo.backend.memory.MemoryBackend;
import org.bson.codecs.configuration.CodecRegistry;
import org.bson.codecs.pojo.PojoCodecProvider;
import org.bson.codecs.pojo.annotations.BsonId;
import org.bson.types.ObjectId;
import org.junit.Test;

import static com.mongodb.client.model.Filters.and;
import static com.mongodb.client.model.Filters.eq;
import static org.bson.codecs.configuration.CodecRegistries.fromProviders;
import static org.bson.codecs.configuration.CodecRegistries.fromRegistries;


public class SecondaryIndexErrorTest {

    @Test
    public void testFailed() {
        MongoCollection<Entity> mongoCollection = createCollection();

        //this line of secondary index breaks tests (!!!!)
        mongoCollection.createIndex(Indexes.ascending("revision"));

        Entity entity = new Entity();
        entity.id = ObjectId.get();
        entity.revision = 1;
        mongoCollection.insertOne(entity);
        entity.revision++;

        mongoCollection.replaceOne(and(
                eq(entity.getId()),
                eq("revision", 1)
        ), entity);
    }

    private MongoCollection<Entity> createCollection() {
        MongoServer mongoServer = new MongoServer(new MemoryBackend());
        MongoClient mongoClient = new MongoClient(new ServerAddress(mongoServer.bind()));
        CodecRegistry codecRegistry = fromRegistries(
                fromProviders(PojoCodecProvider.builder().automatic(true).build()),
                MongoClient.getDefaultCodecRegistry()
        );
        return mongoClient.getDatabase("test").withCodecRegistry(codecRegistry)
                .getCollection("test", Entity.class);
    }

    public static class Entity {

        @BsonId
        private ObjectId id;
        private int revision;

        public ObjectId getId() {
            return id;
        }

        public void setId(ObjectId id) {
            this.id = id;
        }

        public int getRevision() {
            return revision;
        }

        public void setRevision(int revision) {
            this.revision = revision;
        }

    }
}

```

**Comment by eryabitskiy** [comment]
I have investigate code changes. Reason is in AbstractMongoDatabase, these lines:

```
    @VisibleForExternalBackends
    protected Index<P> openOrCreateSecondaryIndex(String collectionName, String indexName, List<IndexKey> keys, boolean sparse) {
        log.warn("adding secondary index with keys {} is not yet implemented. ignoring", keys);
        return new EmptyIndex<>(indexName, keys);
    }
```

before it was:

```
    @VisibleForExternalBackends
    protected Index<P> openOrCreateSecondaryIndex(String collectionName, String indexName, List<IndexKey> keys, boolean sparse) {
        log.warn("adding secondary index with keys {} is not yet implemented. ignoring", keys);
        return null;
    }
```

**Comment by bwaldvogel** [comment]
Thanks for reporting.
We obviously missed a test case for your scenario so I’m glad that we have it now.
It should be fixed in ad45922. Could you check?

**Comment by eryabitskiy** [comment]
Great! Thank you for your fast response.

Regarding commit: From perspective of test case and code looks reasonable.
I will try to check with snapshot build lately.

**Comment by eryabitskiy** [comment]
Great news from my side: I have checked with recent Snapshot build from master. 
No degradation detected with my build / tests.
 I guess we can close this issue. And I am waiting for 1.34 release ;)

**Comment by bwaldvogel** [comment]
Version `1.34.0` is available
