### ISSUE TITLE
no such cmd: listIndexes

### ISSUE THREAD

**Issue by HaVonTe1** [bwaldvogel/mongo-java-server#17]
listIndexes is not yet implemented, I guess :)

```java
07:44:12.982 INFO  [nioEventLoopGroup-3-4]: adding unique index [key] for collection test
07:44:12.987 ERROR [nioEventLoopGroup-3-4]: unknown query: { "listIndexes" : "test"}
07:44:12.992 ERROR [nioEventLoopGroup-3-4]: unknown command: MongoQuery(header: MessageHeader(request: 42, responseTo: 0), collection: test_feeds.$cmd, query: { "listIndexes" : "test"}, returnFieldSelector: { })
de.bwaldvogel.mongo.exception.NoSuchCommandException: no such cmd: listIndexes
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.handleCommand(AbstractMongoDatabase.java:148) ~[mongo-java-server-core-1.4.1.jar:na]
	at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleCommand(AbstractMongoBackend.java:130) ~[mongo-java-server-core-1.4.1.jar:na]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleCommand(MongoDatabaseHandler.java:147) [mongo-java-server-core-1.4.1.jar:na]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleQuery(MongoDatabaseHandler.java:97) [mongo-java-server-core-1.4.1.jar:na]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:73) [mongo-java-server-core-1.4.1.jar:na]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:37) [mongo-java-server-core-1.4.1.jar:na]

```

**Comment by bwaldvogel** [comment]
Could you re-test the issue on 86d976a?

**Comment by bwaldvogel** [comment]
mongo-java-server v1.4.2 is released and contains the fix
