### ISSUE TITLE
Crash when creating indexes concurrently

### ISSUE THREAD

**Issue by ninja-** [bwaldvogel/mongo-java-server#195]
```
[mongo-server-worker11] ERROR de.bwaldvogel.mongo.wire.MongoWireProtocolHandler - Unknown error!
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1604)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	**at de.bwaldvogel.mongo.backend.AbstractMongoCollection.findByName(AbstractMongoCollection.java:224)
	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.addIndex(AbstractMongoCollection.java:197)
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.openOrCreateIndex(AbstractMongoDatabase.java:827)
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.addIndex(AbstractMongoDatabase.java:803)
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.commandCreateIndexes(AbstractMongoDatabase.java:421)**
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.handleCommandSync(AbstractMongoDatabase.java:123)
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.lambda$handleCommandAsync$1(AbstractMongoDatabase.java:200)
	at de.bwaldvogel.mongo.util.FutureUtils.wrap(FutureUtils.java:9)
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.handleCommandAsync(AbstractMongoDatabase.java:200)
	at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleCommandAsync(AbstractMongoBackend.java:376)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleCommandAsync(MongoDatabaseHandler.java:254)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleQueryAsync(MongoDatabaseHandler.java:120)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:73)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:34)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by bwaldvogel** [comment]
I just released version `1.40.0` which should fix this potential concurrency issue. Can you verify it?

**Comment by ninja-** [comment]
the issues is fixed, thank you
