### ISSUE TITLE
Issue while creating In memory DB 

### ISSUE THREAD

**Issue by gargipande** [bwaldvogel/mongo-java-server#27]
Hi, 

I am new to mongo DB. 
Have a requirement where have to create in memory mongo db. Was trying to use the SimpleTest from the repository. I didn't modified any thing. Getting Time out error while executing the test case. 

com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:54689, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message}, caused by {java.net.SocketTimeoutException: Read timed out}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:375)
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:104)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:203)
	at com.mongodb.operation.CountOperation.execute(CountOperation.java:207)
	at com.mongodb.operation.CountOperation.execute(CountOperation.java:54)
	at com.mongodb.Mongo.execute(Mongo.java:818)
	at com.mongodb.Mongo$2.execute(Mongo.java:805)
	at com.mongodb.MongoCollectionImpl.count(MongoCollectionImpl.java:185)
	at com.mongodb.MongoCollectionImpl.count(MongoCollectionImpl.java:165)
	at com.cisco.SimpleTest.testSimpleInsertQuery(SimpleTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

Thanks in advance.

**Comment by bwaldvogel** [comment]
I cannot reproduce your issue. `SimpleTest` runs fine for me.
Please provide more specific steps to reproduce.

**Comment by gargipande** [comment]
[SimpleTest.java.zip](https://github.com/bwaldvogel/mongo-java-server/files/2244520/SimpleTest.java.zip)
Attached is the Class. Added required jars in class path and then trying to execute the Junit.

**Comment by bwaldvogel** [comment]
Please configure logging (if not done already) and attach the logfile.

**Comment by gargipande** [comment]
[Archive.zip](https://github.com/bwaldvogel/mongo-java-server/files/2244806/Archive.zip)

PFA the log and the class.

**Comment by bwaldvogel** [comment]
mongo-java-server uses slf4j. Please configure slf4j with log4j or slf4j with logback.

**Comment by gargipande** [comment]
Thanks it worked. One of the netty jar was old. So method was missing. Came to know from log files.
