### ISSUE TITLE
Missing query operator '$or'

### ISSUE THREAD

**Issue by alperenp** [bwaldvogel/mongo-java-server#42]
Greetings,

I'm using your nice mockup library to test my classes. However, I realized that mongo server throws exception due to missing operator. Maybe you would like to consider adding this in your coming updates

```
2019-01-07 16:56:58.509 ERROR [d.b.mongo.wire.MongoWireProtocolHandler:103] - failed to handle query MongoQuery(header: MessageHeader(request: 26, responseTo: 0), collection: <myCollectionName>, query: <myMongoQuery>, returnFieldSelector: null)
de.bwaldvogel.mongo.exception.MongoServerError: [Error 2] unknown operator: $or
	at de.bwaldvogel.mongo.backend.QueryOperator.fromValue(QueryOperator.java:49)
	at de.bwaldvogel.mongo.backend.DefaultQueryMatcher.checkExpressionMatch(DefaultQueryMatcher.java:377)
	at de.bwaldvogel.mongo.backend.DefaultQueryMatcher.checkMatchesValue(DefaultQueryMatcher.java:310)
	at de.bwaldvogel.mongo.backend.DefaultQueryMatcher.checkMatchesElemValues(DefaultQueryMatcher.java:354)
	at de.bwaldvogel.mongo.backend.DefaultQueryMatcher.checkMatchesAnyValue(DefaultQueryMatcher.java:175)
	at de.bwaldvogel.mongo.backend.DefaultQueryMatcher.checkMatch(DefaultQueryMatcher.java:151)
	at de.bwaldvogel.mongo.backend.DefaultQueryMatcher.checkMatch(DefaultQueryMatcher.java:81)
	at de.bwaldvogel.mongo.backend.DefaultQueryMatcher.matches(DefaultQueryMatcher.java:32)
	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.documentMatchesQuery(AbstractMongoCollection.java:46)
	at de.bwaldvogel.mongo.backend.memory.MemoryCollection.matchDocuments(MemoryCollection.java:96)
	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.queryDocuments(AbstractMongoCollection.java:59)
	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.handleQuery(AbstractMongoCollection.java:710)
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.handleQuery(AbstractMongoDatabase.java:645)
	at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleQuery(AbstractMongoBackend.java:206)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleQuery(MongoDatabaseHandler.java:93)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:71)
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:37)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by alperenp** [comment]
Here is a sample class that gives the same exception for '$or' operator

```
/**
 * 
 * @author alperenp
 *
 */
public class MinimalTest {
	private MongoServer server;
	private MongoClient client;
	private MongoCollection<Document> collection;
	
	@Before
	public void init() throws IOException {
		server = new MongoServer(new MemoryBackend());
		
		// bind on a random local port
		InetSocketAddress serverAddress = server.bind();
		
		client = new MongoClient(new ServerAddress(serverAddress));
		collection = client.getDatabase("testdb").getCollection("testcollection");
	}
	
	@After
	public void tearDown() {
		client.close();
		server.shutdown();
	}
	
	@Test
	public void testSimpleInsertAndSearchQuery() throws Exception {
		Document obj = new Document("_id", 1).append("key", "value").append("languages",
				Arrays.asList("Java", "C#", "C", "C++"));
		collection.insertOne(obj);
		List<String> ids = Arrays.asList(new String[] { "C", "Java" });
		Set<String> items = search(ids);
		items.forEach(item -> System.out.println(item));
	}
	
	private Set<String> search(Collection<String> values) {
		Bson query = buildQuery(values);
		return queryDatabase(query);
	}
	
	private Bson buildQuery(Collection<String> values) {
		Bson[] filters = values.stream().map(this::buildQuery).collect(Collectors.toList())
				.toArray(new Bson[values.size()]);
		Bson query = Filters.elemMatch("languages", Filters.or(filters));
		return query;
	}
	
	private Bson buildQuery(String value) {
		BsonDocument values = new BsonDocument();
		values.append("key", new BsonString(value.toString()));
		return values;
	}
	
	private Set<String> queryDatabase(Bson query) {
		FindIterable<Document> iterable = collection.find(query);
		Set<String> queryResult = new HashSet<>();
		try (MongoCursor<Document> result = iterable.iterator()) {
			while (result.hasNext()) {
				queryResult.add((result.next().getString("key")));
			}
			return queryResult;
		}
	}
}
```

**Comment by bwaldvogel** [comment]
205074c should fix this bug. Can you retest?
