### ISSUE TITLE
java.lang.UnsupportedOperationException: can't sort class java.util.UUID

### ISSUE THREAD

**Issue by belas89** [bwaldvogel/mongo-java-server#44]
**Test Case:**

1. Store in database two documents with UUID type as id
2. Perform distinct operation with UUID.class result type
Currently test will fail with error:
> java.lang.UnsupportedOperationException: can't sort class java.util.UUID
> 	at de.bwaldvogel.mongo.backend.ValueComparator.getTypeOrder(ValueComparator.java:141)
> 	at de.bwaldvogel.mongo.backend.ValueComparator.compare(ValueComparator.java:65)
> 	at java.util.TreeMap.put(TreeMap.java:552)
> 	at java.util.TreeSet.add(TreeSet.java:255)
> 	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.handleDistinct(AbstractMongoCollection.java:776)
> 	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.handleCommand(AbstractMongoDatabase.java:141)
> 	at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleCommand(AbstractMongoBackend.java:193)
> 	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleCommand(MongoDatabaseHandler.java:149)
> 	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleQuery(MongoDatabaseHandler.java:91)

**Test code:**
```
package my.test;

import com.mongodb.MongoClient;
import com.mongodb.ServerAddress;
import de.bwaldvogel.mongo.MongoServer;
import de.bwaldvogel.mongo.backend.memory.MemoryBackend;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsInAnyOrder;

public class DistinctUUIDTest {
    private MongoServer server;
    private MongoClient client;
    private MongoTemplate mongoTemplate;

    @Before
    public void init() {
        server = new MongoServer(new MemoryBackend());
        client = new MongoClient(new ServerAddress(server.bind()));
        mongoTemplate = new MongoTemplate(client, "uuidDatabase");
    }


    @After
    public void cleanup() {
        client.close();
        server.shutdown();
    }

    @Test
    public void systemSupportsDistinctWithUUIDResultType() {
        final TestEntity first = mongoTemplate.save(new TestEntity(UUID.randomUUID(), "first"), "test");
        final TestEntity second = mongoTemplate.save(new TestEntity(UUID.randomUUID(), "second"), "test");

        final List<UUID> ids = mongoTemplate.getCollection("test").distinct("_id", UUID.class).into(new ArrayList<>());
        assertThat(ids, containsInAnyOrder(first.getId(), second.getId()));
    }

    @Document(collection = "test")
    public static class TestEntity {
        @Id
        private UUID id;
        private String name;

        public TestEntity() {
        }

        public TestEntity(UUID id, String name) {
            this.id = id;
            this.name = name;
        }

        public UUID getId() {
            return id;
        }

        public String getName() {
            return name;
        }

        public void setId(UUID id) {
            this.id = id;
        }

        public void setName(String name) {
            this.name = name;
        }
    }
}

```
**It looks like** UUID type is not supported in ValueComparator class.  Could you fix it or explain why it cannot work? We used Fongo earlier, and the test worked there.

**Comment by belas89** [comment]
Any news?

**Comment by bwaldvogel** [comment]
Thanks for the bug report. I’m working on the fix and plan to push it soon…

**Comment by bwaldvogel** [comment]
Can you retest on 982f4ca?

**Comment by belas89** [comment]
Great, it works as expected, thanks a lot!

**Comment by bwaldvogel** [comment]
Version `1.12.0` contains the fix.
