### ISSUE TITLE
DECIMAL128 is not supported

### ISSUE THREAD

**Issue by belas89** [bwaldvogel/mongo-java-server#45]
mongo-java-driver contains logic to read [Decimal128](https://github.com/mongodb/specifications/blob/master/source/bson-decimal128/decimal128.rst) values: https://github.com/mongodb/mongo-java-driver/blob/master/bson/src/main/org/bson/AbstractBsonWriter.java#L873

But https://github.com/bwaldvogel/mongo-java-server/blob/master/core/src/main/java/de/bwaldvogel/mongo/wire/BsonDecoder.java does not support it.

As result query like 
`{ "singleNumberField" : { "$eq" : { "$numberDecimal" : "1" } } }`
will fail with

```
Caused by: java.io.IOException: unknown type: 0x13
	at de.bwaldvogel.mongo.wire.BsonDecoder.decodeValue(BsonDecoder.java:99)
	at de.bwaldvogel.mongo.wire.BsonDecoder.decodeBson(BsonDecoder.java:38)
	at de.bwaldvogel.mongo.wire.BsonDecoder.decodeValue(BsonDecoder.java:54)
	at de.bwaldvogel.mongo.wire.BsonDecoder.decodeBson(BsonDecoder.java:38)
	at de.bwaldvogel.mongo.wire.MongoWireProtocolHandler.handleQuery(MongoWireProtocolHandler.java:175)
	at de.bwaldvogel.mongo.wire.MongoWireProtocolHandler.decode(MongoWireProtocolHandler.java:88)
	at de.bwaldvogel.mongo.wire.MongoWireProtocolHandler.decode(MongoWireProtocolHandler.java:26)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:343)
```

**Comment by bwaldvogel** [comment]
Thanks for the report. It’s not yet implemented. Willing to submit a PR?

**Comment by bwaldvogel** [comment]
Can you retest on 418bba3?

**Comment by belas89** [comment]
Result contains redundant entities if try to perform search by integer array field, eg.

- Entity class has field: List<Integer> multipleNumberField
- Entities in DB: 
 {id: someValue, multipleNumberField : [-1]}
 {id: someValue, multipleNumberField : [0]}
- Query: {"multipleNumberField" : {"$ne" : 0}}
ER: Only first entity is in result.
AR: Both entities will be in result.

If query will be {"multipleNumberField" : {"$eq" : 0}} it works fine.

**Comment by bwaldvogel** [comment]
Actually, this is a different issue. Can you retest on da231b8?

**Comment by belas89** [comment]
Sure. Retested on mentioned revision. Passed. 
Could you release the library?

**Comment by bwaldvogel** [comment]
Yes, I’m planning to release in the next days.

**Comment by bwaldvogel** [comment]
Version `1.12.0` contains the fix.
