### ISSUE TITLE
"Prematurely reached end of stream" (Compound Indexes Unsupported)

### ISSUE THREAD

**Issue by NfNitLoop** [bwaldvogel/mongo-java-server#80]
We tried to switch from fongo to mongo-java-server, but several of our unit tests were failing and we couldn't figure out why.   On the test side, we were seeing this error:

```
com.mongodb.MongoSocketReadException: Prematurely reached end of stream

	at com.mongodb.connection.SocketStream.read(SocketStream.java:88)
	at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:494)
	at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:224)
	at com.mongodb.connection.UsageTrackingInternalConnection.receiveMessage(UsageTrackingInternalConnection.java:96)
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection.receiveMessage(DefaultConnectionPool.java:440)
	at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:289)
	at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:54)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
	at com.mongodb.connection.DefaultServerConnection.query(DefaultServerConnection.java:212)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:525)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:510)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:431)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:404)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:510)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:81)
	at com.mongodb.Mongo.execute(Mongo.java:836)
	at com.mongodb.Mongo$2.execute(Mongo.java:823)
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:870)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:142)
[snip]
```

When we finally figured out that we'd need to turn on server-side logging, and how to do so, we found the real culprit:

```
07/16 12:41:53,358 ERROR de.bwaldvogel.mongo.wire.MongoExceptionHandler - exception for client bb636684
java.lang.UnsupportedOperationException: Not yet implemented
        at de.bwaldvogel.mongo.backend.AbstractUniqueIndex.getPositions(AbstractUniqueIndex.java:147)
        at de.bwaldvogel.mongo.backend.AbstractMongoCollection.queryDocuments(AbstractMongoCollection.java:47)
        at de.bwaldvogel.mongo.backend.AbstractMongoCollection.handleQuery(AbstractMongoCollection.java:330)
        at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.handleQuery(AbstractMongoDatabase.java:664)
        at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleQuery(AbstractMongoBackend.java:206)
        at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleQuery(MongoDatabaseHandler.java:93)
        at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:71)
        at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:37)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:745)

```

Some of our test setup code added compound indexes to the (MemoryBackend) MongoServer.

The server accepts those indexes, but when it tries to use them later, it causes an error. The error-at-a-distance behavior made it difficult to figure out the cause.

It seems like this should be easy to fix.   In `AbstractUniqueIndex.canHandle(query)`, it could just return `false` if `isCompoundIndex()`, so that `AbstractMongoCollection` can fall back to some other index, or no index.

i.e.: Don't try to use the unsupported indexes. Don't raise an exception that causes the server to prematurely drop the connection.

Another option would be to raise the UnsupportedOperationException earlier, when users try adding them. That would make it clear what the real problem is.  (I'd prefer not to go this route, though, as it means we'll have to add different indexes depending on if we're testing against real mongo or mongo-java-server.)

**Comment by NfNitLoop** [comment]
I went ahead and made a fix to this. Putting up the PR now.  I see you just released 1.17 earlier today. Can I bribe you somehow to make a new release with these changes soon? :)  It's blocking us from adopting mongo-java-server.

**Comment by bwaldvogel** [comment]
> I see you just released 1.17 earlier today

Yes, it was unlucky timing ;)

I’ve just released `1.17.1` which contains your PR.

**Comment by bwaldvogel** [comment]
> When we finally figured out that we'd need to turn on server-side logging, and how to do so, […]

Is there something we could add to the README to help other people in this regard?

**Comment by NfNitLoop** [comment]
> Is there something we could add to the README to help other people in this regard?

Ehhh... in hindsight, I think the issue was me just being new to this project. It turns out errors *were* being logged, but they'd been redirected to a file, so weren't readily available in JUnit's output. Turns out it's hard to debug an issue if you can't see all the error messages. 🤦‍♂ 

Thanks for the quick turnaround! We've updated to the latest version and confirmed that everything now works for us! 🎉
