### ISSUE TITLE
NPE when updating a document with nullable indexed property.

### ISSUE THREAD

**Issue by arongas** [bwaldvogel/mongo-java-server#90]
I have an indexed property in a document. 
    @Indexed(unique = true, sparse = true)
    @Nullable
    private String data;

I index the document and the first time this property is null.
I then update the property with some value. At this point i get the following exception.

`java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[na:1.8.0_152]
	at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1535) ~[na:1.8.0_152]
	at de.bwaldvogel.mongo.backend.memory.index.MemoryUniqueIndex.putKeyPosition(MemoryUniqueIndex.java:42) ~[mongo-java-server-memory-backend-1.19.0.jar:na]
	at de.bwaldvogel.mongo.backend.memory.index.MemoryUniqueIndex.putKeyPosition(MemoryUniqueIndex.java:12) ~[mongo-java-server-memory-backend-1.19.0.jar:na]
	at de.bwaldvogel.mongo.backend.AbstractUniqueIndex.add(AbstractUniqueIndex.java:86) ~[mongo-java-server-core-1.19.0.jar:na]
	at de.bwaldvogel.mongo.backend.AbstractUniqueIndex.updateInPlace(AbstractUniqueIndex.java:120) ~[mongo-java-server-core-1.19.0.jar:na]
	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.updateDocument(AbstractMongoCollection.java:478) ~[mongo-java-server-core-1.19.0.jar:na]
	at de.bwaldvogel.mongo.backend.AbstractMongoCollection.updateDocuments(AbstractMongoCollection.java:440) ~[mongo-java-server-core-1.19.0.jar:na]
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.updateDocuments(AbstractMongoDatabase.java:879) ~[mongo-java-server-core-1.19.0.jar:na]
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.commandUpdate(AbstractMongoDatabase.java:295) ~[mongo-java-server-core-1.19.0.jar:na]
	at de.bwaldvogel.mongo.backend.AbstractMongoDatabase.handleCommand(AbstractMongoDatabase.java:131) ~[mongo-java-server-core-1.19.0.jar:na]
	at de.bwaldvogel.mongo.backend.AbstractMongoBackend.handleCommand(AbstractMongoBackend.java:197) ~[mongo-java-server-core-1.19.0.jar:na]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleCommand(MongoDatabaseHandler.java:153) ~[mongo-java-server-core-1.19.0.jar:na]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.handleQuery(MongoDatabaseHandler.java:90) ~[mongo-java-server-core-1.19.0.jar:na]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:70) ~[mongo-java-server-core-1.19.0.jar:na]
	at de.bwaldvogel.mongo.wire.MongoDatabaseHandler.channelRead0(MongoDatabaseHandler.java:36) ~[mongo-java-server-core-1.19.0.jar:na]`

I debuged a liitle and the reason is that possition is null in the method de.bwaldvogel.mongo.backend.memory.index.MemoryUniqueIndex#putKeyPosition.

My version is de.bwaldvogel:mongo-java-server:1.19.0'

**Comment by bwaldvogel** [comment]
Thanks for reporting this issue. Can you re-test on c01e20d?

**Comment by arongas** [comment]
Yes it seems to be working

**Comment by spirosag** [comment]
@bwaldvogel a somewhat offtopic question. 
I wanted to import this latest version in my project but I faced the problem that if I just added the .jars produced by `gradlew jar` they didn't include their own dependencies (that would be brought from the mvn repository).
I ended up using [the shadow plugin](/johnrengelman/shadow) to create a super fat jar containing everything.
It seemed to work but I was wondering there is another way to do it already built in your project?

**Comment by bwaldvogel** [comment]
@spirosag: I could have published a snapshot version but that wouldn’t help if someone wants to modify mongo-java-server locally to try something out.
Maybe it would be helpful for others to include something like the [the shadow plugin](https://github.com/johnrengelman/shadow)?
Are you interested to submit a PR?

**Comment by bwaldvogel** [comment]
The fix is released in version `1.20.0`.
